version: 2
updates:
  - package-ecosystem: "helm" # See documentation for possible values
    directories: 
      - "/charts/*"
      - "/"
    schedule:
      interval: "weekly"
    labels:
      - "helm"
      - "dependencies"
      
