faaast-service:
  messageBus:
    host: "wss://<path:factory-x-ci-cd/data/async-aas#broker-url>:443"
    user: "<path:factory-x-ci-cd/data/async-aas#broker-user>"
    password: "<path:factory-x-ci-cd/data/async-aas#broker-pw>"

aas-basyx-v2-full:
  mqtt:
    enabled: true
    websockets:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
       kubernetes.io/ingress.class: nginx
       kubernetes.io/tls-acme: "true"
       nginx.ingress.kubernetes.io/enable-cors: "true"
       cert-manager.io/cluster-issuer: "letsencrypt-prod"
       nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
       nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
       nginx.ingress.kubernetes.io/websocket-services: mqttbroker-websockets-service
      hosts:
        - host: <path:factory-x-ci-cd/data/async-aas#broker-url>
          type: websockets
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: chart-example-tls
          hosts:
            - <path:factory-x-ci-cd/data/async-aas#broker-url>
    apirules: []
    auth:
      enabled: true
      users:
        - username: fx-factory
          password: <path:factory-x-ci-cd/data/async-aas#broker-pw-hash>
          acl:
            - topic: "#"
              access: readwrite
        - username: fx-publisher
          password: <path:factory-x-ci-cd/data/async-aas#broker-pw-hash>
          acl:
            - topic: "#"
              access: readwrite
        - username: fx-subscriber
          password: <path:factory-x-ci-cd/data/async-aas#broker-pw-hash>
          acl:
            - topic: "#"
              access: readwrite
        - username: fx-factory2
          password: <path:factory-x-ci-cd/data/async-aas#broker-pw-hash>
          acl:
            - topic: "#"
              access: readwrite
        - username: fx-publisher2
          password: <path:factory-x-ci-cd/data/async-aas#broker-pw-hash>
          acl:
            - topic: "#"
              access: readwrite
        - username: fx-subscriber2
          password: <path:factory-x-ci-cd/data/async-aas#broker-pw-hash>
          acl:
            - topic: "#"
              access: readwrite

  keycloak:
    enabled: false

  aas-registry:
    enabled: true
    image:
            # If Kafka is used, then the appropriate Bootstrap connection string must be provided.
      name: eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT
      pullPolicy: IfNotPresent
    service:
      port: 8080
    # Keep it null if not deploying a Kafka instance.
    kafka:
      connectionString: null
    ingress:
      enabled: true
      host: <path:factory-x-ci-cd/data/async-aas#basyx-reg-url>
    config: |-
      basyx:
        cors:
          allowed-origins: "*"
          allowed-methods: "GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD"


  sm-registry:
    enabled: false

  aas-discovery:
    enabled: true
    image:
      name: eclipsebasyx/aas-discovery:2.0.0-SNAPSHOT
      pullPolicy: IfNotPresent
    service:
      port: 8081
    config: |-
      server.port=8081
      spring.application.name=AAS Discovery Service

      basyx.aasdiscoveryservice.name=aas-discovery-service

      basyx.backend=InMemory

      basyx.cors.allowed-origins=*
      basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD

      basyx.feature.authorization.enabled = false
      basyx.feature.authorization.type = rbac
      basyx.feature.authorization.jwtBearerTokenProvider = keycloak
      basyx.feature.authorization.rbac.file = file:/application/rbac_rules.json
      spring.security.oauth2.resourceserver.jwt.issuer-uri = http://basyx-keycloak.basyx.svc.cluster.local:8080/realms/BaSyx
    ingress:
      enabled: true
      host: <path:factory-x-ci-cd/data/async-aas#basyx-disco-url>

  # Also needs an ingress.
  aas-environment:
    enabled: true
    image:
      name: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
      pullPolicy: Always
    service:
      port: 8081
    config: |-
      server.port=8081

      basyx.backend = InMemory

      #basyx.environment=file:aas

      logging.level.root=DEBUG

      basyx.cors.allowed-origins=*
      basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      basyx.aasrepository.feature.registryintegration=https://<path:factory-x-ci-cd/data/async-aas#basyx-reg-url>
      basyx.externalurl=https://<path:factory-x-ci-cd/data/async-aas#basyx-env-url>
      spring.servlet.multipart.max-file-size=128MB
      spring.servlet.multipart.max-request-size=128MB

      basyx.aasrepository.feature.mqtt.enabled = true
      basyx.submodelrepository.feature.mqtt.enabled = true
      mqtt.clientId=basyx
      mqtt.hostname=<path:factory-x-ci-cd/data/async-aas#broker-url>
      mqtt.protocol=wss
      mqtt.port=443
      mqtt.username=<path:factory-x-ci-cd/data/async-aas#broker-user>
      mqtt.password=<path:factory-x-ci-cd/data/async-aas#broker-pw>
    ingress:
      enabled: true
      host: <path:factory-x-ci-cd/data/async-aas#basyx-env-url>

  # Needs specific ingress.
  aas-web-ui:
    enabled: false
