apiVersion: v1
kind: Secret
metadata:
  name: faaast-registry-basic-auth-secret
type: Opaque
data:
  auth: {{ printf "%s:%s" (index .Values "faaast-registry" "ingress" "basicAuth" "user") (index .Values "faaast-registry" "ingress" "basicAuth" "htPassword") | b64enc | quote }}